import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    '.old',
    '.v2-extras',
    'public',
    'src/routeTree.gen.ts',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Underscore prefix is the project convention for intentionally
      // unused parameters / catch bindings / destructured holes.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
        },
      ],
      // TanStack Router file-routes export `Route = createFileRoute(...)({…})`
      // and colocate the component the route renders. Tag `createFileRoute`
      // as a HOC so the plugin sees Route as a component export and stops
      // warning about the colocated component. `allowExportNames` is NOT used
      // here because it short-circuits before the HOC check and would leave
      // the route's local component flagged.
      'react-refresh/only-export-components': [
        'error',
        {
          allowConstantExport: true,
          // shadcn theme-provider co-exports the `useTheme` hook with the
          // provider component — explicit allow keeps the pattern intact.
          allowExportNames: ['useTheme'],
        },
      ],
    },
  },
  {
    // shadcn-generated UI primitives co-export variants (cva), contexts,
    // and helper hooks next to the component. Fast-Refresh restrictions
    // don't apply to these — they're auto-regenerated by `shadcn add`,
    // not hand-edited during HMR sessions.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
  {
    // TanStack Router file-routes idiomatically co-export `Route` (object
    // returned by `createFileRoute`/`createRootRoute`) with the route's
    // component. `createFileRoute` is NOT a React HOC — gaming it via
    // `extraHOCs` makes the rule pass but the eslint-plugin-react-refresh
    // maintainer warns it can degrade HMR over time. Disable the rule for
    // the routes directory instead; route files are small and visually
    // distinct, so the Fast-Refresh signal isn't pulling weight here.
    files: ['src/routes/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
