/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IcPersonRouteImport } from './routes/ic.$person'
import { Route as IcPersonIndexRouteImport } from './routes/ic.$person.index'
import { Route as IcPersonTeamRouteImport } from './routes/ic.$person.team'
import { Route as IcPersonPersonalRouteImport } from './routes/ic.$person.personal'

const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IcPersonRoute = IcPersonRouteImport.update({
  id: '/ic/$person',
  path: '/ic/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const IcPersonIndexRoute = IcPersonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IcPersonRoute,
} as any)
const IcPersonTeamRoute = IcPersonTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => IcPersonRoute,
} as any)
const IcPersonPersonalRoute = IcPersonPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => IcPersonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/whats-new': typeof WhatsNewRoute
  '/ic/$person': typeof IcPersonRouteWithChildren
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/ic/$person/': typeof IcPersonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/whats-new': typeof WhatsNewRoute
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/ic/$person': typeof IcPersonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/whats-new': typeof WhatsNewRoute
  '/ic/$person': typeof IcPersonRouteWithChildren
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/ic/$person/': typeof IcPersonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/whats-new'
    | '/ic/$person'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/ic/$person/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/whats-new'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/ic/$person'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/whats-new'
    | '/ic/$person'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/ic/$person/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  WhatsNewRoute: typeof WhatsNewRoute
  IcPersonRoute: typeof IcPersonRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ic/$person': {
      id: '/ic/$person'
      path: '/ic/$person'
      fullPath: '/ic/$person'
      preLoaderRoute: typeof IcPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ic/$person/': {
      id: '/ic/$person/'
      path: '/'
      fullPath: '/ic/$person/'
      preLoaderRoute: typeof IcPersonIndexRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/ic/$person/team': {
      id: '/ic/$person/team'
      path: '/team'
      fullPath: '/ic/$person/team'
      preLoaderRoute: typeof IcPersonTeamRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/ic/$person/personal': {
      id: '/ic/$person/personal'
      path: '/personal'
      fullPath: '/ic/$person/personal'
      preLoaderRoute: typeof IcPersonPersonalRouteImport
      parentRoute: typeof IcPersonRoute
    }
  }
}

interface IcPersonRouteChildren {
  IcPersonPersonalRoute: typeof IcPersonPersonalRoute
  IcPersonTeamRoute: typeof IcPersonTeamRoute
  IcPersonIndexRoute: typeof IcPersonIndexRoute
}

const IcPersonRouteChildren: IcPersonRouteChildren = {
  IcPersonPersonalRoute: IcPersonPersonalRoute,
  IcPersonTeamRoute: IcPersonTeamRoute,
  IcPersonIndexRoute: IcPersonIndexRoute,
}

const IcPersonRouteWithChildren = IcPersonRoute._addFileChildren(
  IcPersonRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  WhatsNewRoute: WhatsNewRoute,
  IcPersonRoute: IcPersonRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
